<?php

require_once __DIR__ . '/../vendor/scholarslab/bagit/lib/bagit.php';
require_once __DIR__ . '/../vendor/scholarslab/bagit/lib/bagit_utils.php';

class BagitUtil
{
    var $m_InputFiles = array();
    var $m_SystemTempDir;
    var $m_TempResources = array();
    
    public function __construct()
    {
        $this->m_SystemTempDir = sys_get_temp_dir();
    }

    public function __destruct()
    {
        // \todo Delete temp files
    }

    public function addFile($filePath)
    {
        array_push($this->m_InputFiles, $filePath);
    }

    public function createBag($outputFile)
    {
        $outputFileExtension = pathinfo($outputFile, PATHINFO_EXTENSION);
        $outputFileWithoutExtension = substr($outputFile, 0, strlen($outputFile) - strlen($outputFileExtension) - 1);
    
        // Create temp directory
        if (!$this->createTempDir($tempDir))
        {
            return false;
        }

        // Create empty bag
        $bagPath = $tempDir . '/' . basename($outputFileWithoutExtension);
        $bag = new BagIt($bagPath);

        // Change bagit version
        $bag->bagVersion = array('major' => 0, 'minor' => 97);
        $bagitTxtPath = $bag->getDataDirectory() . '/../bagit.txt';
        $bagitTxtContent = file_get_contents($bagitTxtPath);
        $bagitTxtContent = str_replace('0.96', '0.97', $bagitTxtContent, $replaceCount);
        if ($replaceCount != 1)
        {
            return false;
        }
        if (file_put_contents($bagitTxtPath, $bagitTxtContent, LOCK_EX) === false)
        {
            return false;
        }

        // Add optional info to bag-info.txt
        $bag->setBagInfoData('Source-Organization', 'Piql');
        $bag->setBagInfoData('Bagging-Date', date("Y-m-d"));
        $bag->setBagInfoData('External-Description', 'Generated by Piql Connect');
        
        // Validate bag
        if (!$bag->isValid() || !$bag->isExtended())
        {
            return false;
        }
        $bagInfo = $bag->getBagInfo();
        if ($bagInfo['version'] != '0.97' || $bagInfo['encoding'] != 'UTF-8' || $bagInfo['hash'] != 'sha1')
        {
            return false;
        }

        // Add data
        foreach ($this->m_InputFiles as $inputFile)
        {
            $bag->addFile($inputFile, 'data/' . basename($inputFile));
        }

        // Update bag with added files
        $bag->update();

        if ($outputFileExtension != 'zip' && $outputFileExtension != 'tgz')
        {
            return false;
        }

        // Output packaged file
        $bag->package($outputFile, $outputFileExtension);

        // Validate created bag
        $createdBag = new BagIt($outputFile);
        $expectedContent = "BagIt-Version: 0.97\n" . "Tag-File-Character-Encoding: UTF-8\n";
        if (file_get_contents($createdBag->bagitFile) != $expectedContent)
        {
            return false;
        }
        $createdBag->validate();
        if (count($createdBag->bagErrors) != 0)
        {
            return false;
        }

        return true;
    }

    private function createTempDir(&$retTempDir)
    {
        if (!is_dir($this->m_SystemTempDir))
        {
            return false;
        }

        $tempDir = $this->m_SystemTempDir . "/" . substr(md5(rand()), 0, 7);
        
        if (!mkdir($tempDir))
        {
            return false;
        }

        array_push($this->m_TempResources, $tempDir);
        $retTempDir = $tempDir;
        return true;
    }
}

?>
