version: '3.6'
services:
    nginx:
      image:  nginx
      restart: unless-stopped
      tty: true
      ports:
        - "80:8040"
        - "443:8443"
      volumes:
            - ./public:/var/www/html
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            #TODO: - ./nginx/ssl/:/etc/nginx/ssl/
       links:
            - app
    app:
        build:
            network: host
            context: ./
            dockerfile: deploy/app.docker
        volumes:
            - "./:/var/www"
        links:
            - database
            - cache
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
    database:
        image: mariadb
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=connect"
            - "MYSQL_USER=connectdbuser"
            - "MYSQL_PASSWORD=AeJua4le"
        ports:
            - "33061:3306"
        volumes:
            - ./storage/db:/var/lib/mysql
    cache:
        image: redis
        ports:
            - "63791:6379"
