<?php

namespace Tests\Unit;

use App\Bag;
use App\File;
use App\Listeners\ArchivematicaClient;
use App\Listeners\ArchivematicaServiceConnection;
use App\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Mockery;
use Tests\TestCase;

class ArchivematicaClientTest extends TestCase
{
    use DatabaseTransactions;
    protected $bag;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = factory(User::class)->create();
        $bag = factory(Bag::class)->create([
            "owner" => $user->id,
            "status" => "move_to_outbox"
        ]);

        $this->files = factory(File::class, 1)->create()->each(function($file) use ($bag) {
            $file->bag_id = $bag->id;
            $file->save();
        });

        $this->bag = $bag->fresh();
    }

    public function test_initiate_transfer()
    {
        // setup
        $serviceConnection = Mockery::mock(ArchivematicaServiceConnection::class);
        $closure = function($method, $uri, array $options = []) {
            return (
                ($method == 'POST') &&
                ($uri == 'transfer/start_transfer/') &&
                ($options['form_params']['name'] == $this->bag->name) &&
                ($options['form_params']['paths[]'] != '') &&
                ($options['form_params']['row_ids[]'] == '')
            );
        };
        $serviceConnection->shouldReceive('doRequest')->once()->withArgs($closure);
        $amClient = new  ArchivematicaClient($serviceConnection);
        $amClient->initiateTransfer($this->bag->name, $this->bag->uuid, $this->bag->zipBagFileName());
    }

    public function test_get_unapproved_list()
    {
        // setup
        $serviceConnection = Mockery::mock(ArchivematicaServiceConnection::class);
        $closure = function($method, $uri, array $options = []) {
            return (
                ($method == 'GET') &&
                ($uri == 'transfer/unapproved/') &&
                ($options == [])
            );
        };
        $serviceConnection->shouldReceive('doRequest')->once()->withArgs($closure);
        $amClient = new  ArchivematicaClient($serviceConnection);
        $amClient->getUnapprovedList();
    }

    public function test_get_transfer_status()
    {
        // setup
        $serviceConnection = Mockery::mock(ArchivematicaServiceConnection::class);
        $closure = function($method, $uri, array $options = []) {
            return (
                ($method == 'GET') &&
                ($uri == 'transfer/status/') &&
                ($options == [])
            );
        };
        $serviceConnection->shouldReceive('doRequest')->once()->withArgs($closure);
        $amClient = new  ArchivematicaClient($serviceConnection);
        $amClient->getTransferStatus();
    }

    public function test_get_transfer_status_with_uuid()
    {
        // setup
        $serviceConnection = Mockery::mock(ArchivematicaServiceConnection::class);
        $closure = function($method, $uri, array $options = []) {
            return (
                ($method == 'GET') &&
                ($uri == 'transfer/status/'.$this->bag->uuid) &&
                ($options == [])
            );
        };
        $serviceConnection->shouldReceive('doRequest')->once()->withArgs($closure);
        $amClient = new  ArchivematicaClient($serviceConnection);
        $amClient->getTransferStatus($this->bag->uuid);
    }

    public function test_get_ingest_status()
    {
        // setup
        $serviceConnection = Mockery::mock(ArchivematicaServiceConnection::class);
        $closure = function($method, $uri, array $options = []) {
            return (
                ($method == 'GET') &&
                ($uri == 'ingest/status/') &&
                ($options == [])
            );
        };
        $serviceConnection->shouldReceive('doRequest')->once()->withArgs($closure);
        $amClient = new  ArchivematicaClient($serviceConnection);
        $amClient->getIngestStatus();
    }

    public function test_get_ingest_status_with_uuid()
    {
        // setup
        $serviceConnection = Mockery::mock(ArchivematicaServiceConnection::class);
        $closure = function($method, $uri, array $options = []) {
            return (
                ($method == 'GET') &&
                ($uri == 'ingest/status/'.$this->bag->uuid) &&
                ($options == [])
            );
        };
        $serviceConnection->shouldReceive('doRequest')->once()->withArgs($closure);
        $amClient = new  ArchivematicaClient($serviceConnection);
        $amClient->getIngestStatus($this->bag->uuid);
    }

    public function test_approve_transfer()
    {
        // setup
        $serviceConnection = Mockery::mock(ArchivematicaServiceConnection::class);
        $closure = function($method, $uri, array $options = []) {
            return (
                ($method == 'POST') &&
                ($uri == 'transfer/approve/') &&
                ($options['form_params']['type'] == 'zipped bag') &&
                ($options['form_params']['directory'] == $this->bag->zipBagFileName())
            );
        };
        $serviceConnection->shouldReceive('doRequest')->once()->withArgs($closure);
        $amClient = new  ArchivematicaClient($serviceConnection);
        $amClient->approveTransfer($this->bag->zipBagFileName());
    }

    public function test_hide_transfer_status()
    {
        // setup
        $serviceConnection = Mockery::mock(ArchivematicaServiceConnection::class);
        $closure = function($method, $uri, array $options = []) {
            return (
                ($method == 'DELETE') &&
                ($uri == 'transfer/'.$this->bag->uuid.'/delete/') &&
                ($options == [])
            );
        };
        $serviceConnection->shouldReceive('doRequest')->once()->withArgs($closure);
        $amClient = new  ArchivematicaClient($serviceConnection);
        $amClient->hideTransferStatus($this->bag->uuid);
    }

    public function test_hide_ingest_status()
    {
        // setup
        $serviceConnection = Mockery::mock(ArchivematicaServiceConnection::class);
        $closure = function($method, $uri, array $options = []) {
            return (
                ($method == 'DELETE') &&
                ($uri == 'ingest/'.$this->bag->uuid.'/delete/') &&
                ($options == [])
            );
        };
        $serviceConnection->shouldReceive('doRequest')->once()->withArgs($closure);
        $amClient = new  ArchivematicaClient($serviceConnection);
        $amClient->hideIngestStatus($this->bag->uuid);
    }

}
