<?php

namespace Tests\Feature;

use App\Bag;
use App\Jobs\ProcessArchivematicaServiceCallback;
use App\Jobs\TransferPackageToStorage;
use App\Listeners\ArchivematicaServiceConnection;
use App\Services\ArchivematicaConnectionService;
use App\User;
use App\UserSetting;
use Illuminate\Queue\CallQueuedClosure;
use Illuminate\Support\Facades\Queue;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Bus;
use Illuminate\Support\Facades\Event;
use Mockery;
use Tests\TestCase;
use Log;
use Laravel\Passport\Passport;

class ArchivematicaServiceCallbackTest extends TestCase
{
    use DatabaseTransactions;
    private $bag;
    private $packageUuid;
    private $serviceUuid;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Bus::fake();
        $user = factory(User::class)->create();
        Passport::actingAs( $user );

        $this->bag = factory(Bag::class)->create([
            "status" => "initiate_transfer"
        ]);

        $this->packageUuid = 'c2f55dcc-304a-4b04-81a4-fac91fbdac54';
        $this->serviceUuid = '913860d0-020c-11ea-bcdc-d372f426b83d';

    }

    private function getFileDetailsResponse($packageUuid, $bagUuid, $statusCode = 200, $packageType = "AIP") {
        $pattern = '/(\w{4})(\w{4})-(\w{4})-(\w{4})-(\w{4})-(\w{4})(\w{4})(\w{4})/';
        $replacement = '$1/$2/$3/$4/$5/$6/$7/$8';
        $path = preg_replace($pattern, $replacement, $packageUuid);
        $response = json_decode( '{
          "current_full_path": "/var/archivematica/sharedDirectory/www/AIPsStore/'. $path .'/H01-'. $bagUuid .'-'. $packageUuid .'.7z",
          "current_location": "/api/v2/location/ea71f8da-415d-4a2d-8103-f02066a54e2f/",
          "current_path": "'. $path .'/H01-'. $bagUuid .'-'. $packageUuid .'.7z",
          "encrypted": false,
          "misc_attributes": {},
          "origin_pipeline": "/api/v2/pipeline/fdca7d1e-14a7-4f62-b9e2-22f3b6771db9/",
          "package_type": "'. $packageType .'",
          "related_packages": [
        "/api/v2/file/57e2f036-dcf1-464f-a244-159eb6faa2c1/"
    ],
          "replicas": [],
          "replicated_package": null,
          "resource_uri": "/api/v2/file/'. $packageUuid .'/",
          "size": 20564,
          "status": "UPLOADED",
          "uuid": "'. $packageUuid .'"
        }');
        return (object)[
            'contents' => ($statusCode == 200) ? $response : "",
            'statusCode' => $statusCode,
        ];
    }

    public function test_with_valid_package_uuid_and_service_uuid_and_archivematica_returns_valid_AIP_description()
    {
        $storageClient = Mockery::mock( \App\Interfaces\ArchivematicaStorageClientInterface::class );
        $storageClient->shouldReceive('getFileDetails')->once()->andReturn(
            $this->getFileDetailsResponse($this->packageUuid, $this->bag->uuid, 200)
        );

        Log::shouldReceive('info')->times(1)->with(\Mockery::pattern('/^Processing callback for stored package with uuid:/'));
        Log::shouldReceive('info')->times(1)->with(\Mockery::pattern('/^AIP uuid /'));
        Log::shouldReceive('error')->times(0);

        $job = new ProcessArchivematicaServiceCallback( $this->packageUuid );
        $job->handle( $storageClient );

        self::assertEquals($this->packageUuid, $this->bag->storage_properties->aip_uuid);

        Bus::assertDispatched(TransferPackageToStorage::class, function ($job) {
            return true;
        });
    }

    public function test_with_valid_package_uuid_and_service_uuid_and_archivematica_returns_valid_DIP_description()
    {
        $storageClient = Mockery::mock( \App\Interfaces\ArchivematicaStorageClientInterface::class );
        $storageClient->shouldReceive('getFileDetails')->once()->andReturn(
            $this->getFileDetailsResponse($this->packageUuid, $this->bag->uuid, 200, 'DIP')
        );

        Log::shouldReceive('info')->times(1)->with(\Mockery::pattern('/^Processing callback for stored package with uuid:/'));
        Log::shouldReceive('info')->times(1)->with(\Mockery::pattern('/^DIP uuid /'));
        Log::shouldReceive('error')->times(0);

        $job = new ProcessArchivematicaServiceCallback( $this->packageUuid );
        $job->handle( $storageClient );

        self::assertEquals($this->packageUuid, $this->bag->storage_properties->dip_uuid);
        Bus::assertDispatched(TransferPackageToStorage::class, function ($job) {
            return true;
        });
    }

    public function test_with_valid_package_uuid_and_service_uuid_and_archivematica_returns_invalid_package_type()
    {
        $storageClient = Mockery::mock( \App\Interfaces\ArchivematicaStorageClientInterface::class );
        $storageClient->shouldReceive('getFileDetails')->once()->andReturn(
            $this->getFileDetailsResponse($this->packageUuid, $this->bag->uuid, 200, 'x')
        );

        Log::shouldReceive('info')->times(1)->with(\Mockery::pattern('/^Processing callback for stored package with uuid:/'));
        Log::shouldReceive('error')->times(1)->with(\Mockery::pattern('/^Unsupported package type/'));

        $job = new ProcessArchivematicaServiceCallback($this->serviceUuid, $this->packageUuid);
        $job->handle( $storageClient );

        self::assertEquals(null, $this->bag->storage_properties->aip_uuid);
        self::assertEquals(null, $this->bag->storage_properties->dip_uuid);
        Bus::assertNotDispatched(TransferPackageToStorage::class, function ($job) {
            return true;
        });
    }

    public function test_with_invalid_package_uuid_archivematica_returns_404()
    {
        $storageClient = Mockery::mock( \App\Interfaces\ArchivematicaStorageClientInterface::class );
        $storageClient->shouldReceive('getFileDetails')->once()->andReturn(
            $this->getFileDetailsResponse($this->packageUuid, $this->bag->uuid, 404 )
        );

        Log::shouldReceive('info')->times(1)->with(\Mockery::pattern('/^Processing callback for stored package with uuid:/'));
        Log::shouldReceive('error')->times(1)->with(\Mockery::pattern('/^Get file details failed with error code/'));

        $job = new ProcessArchivematicaServiceCallback( $this->packageUuid );
        $job->handle( $storageClient );

        self::assertEquals("", $this->bag->storage_properties->aip_uuid);
        Bus::assertNotDispatched(TransferPackageToStorage::class, function ($job) {
            return true;
        });
    }

    public function test_archivematica_returns_with_no_reference_bag_uuid()
    {

        $storageClient = Mockery::mock( \App\Interfaces\ArchivematicaStorageClientInterface::class );
        $storageClient->shouldReceive('getFileDetails')->once()->andReturn(
            $this->getFileDetailsResponse($this->packageUuid, '57e2f036-dcf1-464f-a244-159eb6faa2c1', 200)
        );

        Log::shouldReceive('info')->times(1)->with(\Mockery::pattern('/^Processing callback for stored package with uuid:/'));
        Log::shouldReceive('error')->times(1)->with(\Mockery::pattern('/^Could not find any storage properties linked to this uuid/'));

        $job = new ProcessArchivematicaServiceCallback( $this->packageUuid );
        $job->handle( $storageClient );

        self::assertEquals(null, $this->bag->storage_properties->aip_uuid);
        Bus::assertNotDispatched(TransferPackageToStorage::class, function ($job) {
            return true;
        });
    }

}
