<?php

namespace Tests\Unit;

use App\ArchivematicaService;
use App\Bag;
use App\Events\ClearIngestStatusEvent;
use App\Events\ClearTmpFilesEvent;
use App\Events\ClearTransferStatusEvent;
use App\Events\IngestCompleteEvent;
use App\Job;
use App\Listeners\ArchivematicaClient;
use App\Listeners\ArchivematicaServiceConnection;
use App\Listeners\IngestCompleteListener;
use App\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Event;
use Tests\TestCase;

class ArchivematicaClientTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function success()
    {

        // setup
        $amClient = new  ArchivematicaClient(new ArchivematicaServiceConnection(ArchivematicaService::first()));
        $bag = Bag::find(1);
        $response = $amClient->initiateTransfer($bag->name, $bag->uuid, $bag->zipBagFileName());
        //$response = $amClient->approveTransfer($bag->zipBagFileName());
        //$response = $amClient->getIngestStatus('b3a0a321-d857-4429-91ac-f28c6b9cb28d');
        //$response = $amClient->getUnapprovedList();
        dd($response);
        $this->json($response);
    }
}
