<?php

namespace Tests\Unit;

use App\Bag;
use App\BagTransitionException;
use Illuminate\Support\Facades\Log;
use Tests\TestCase;
use function Psy\debug;
class TestBag extends Bag {
    public function getSmConfig() {
        return $this->smConfig;
    }
}

class BagTest extends TestCase
{
    private $bag;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->bag = new TestBag([
            'name' => 'Testbag',
            'owner' => 'owner',
        ]);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * @dataProvider validStateTransitionProvider
     */
    public function test_valid_state_transitions($from, $to, $transition) {
        $this->bag->status = $from;
        $this->bag->applyTransition($transition);
        $this->assertEquals($this->bag->status, $to);
    }

    public function validStateTransitionProvider() {

        $bag = new TestBag([
            'name' => 'Testbag',
            'owner' => 'owner',
        ]);
        $smConfig = $bag->getSmConfig();
        $states = $smConfig['states'];
        $transitions = $smConfig['transitions'];
        $testSet = [];
        foreach ($transitions as $key => $transition) {
            foreach ($states as $state) {
                if((array_search($state, $transition["from"]) !== false)) {
                    $testSet += [$key . "_from_state_" . $state => [$state, $transition['to'], $key]];
                }
            }
        }
        return $testSet;
    }

    /**
     * @dataProvider invalidStateTransitionProvider
     */
    public function test_invalid_state_transitions($from, $transition) {
        $this->bag->status = $from;
        $this->expectException(BagTransitionException::class);
        $this->bag->applyTransition($transition);
        $this->assertEquals($this->bag->status, $from);
    }

    public function invalidStateTransitionProvider() {
        $bag = new TestBag([
            'name' => 'Testbag',
            'owner' => 'owner',
        ]);
        $smConfig = $bag->getSmConfig();
        $states = $smConfig['states'];
        $transitions = $smConfig['transitions'];
        $testSet = [];
        foreach ($transitions as $key => $transition) {
            foreach ($states as $state) {
                if((array_search($state, $transition["from"]) === false)) {
                    $testSet += [$key . "_from_state_" . $state => [$state, $key]];
                }
            }
        }
        return $testSet;
    }


}
