<?php

namespace Tests\Unit;

use App\Events\OrganizationCreatedEvent;
use App\Organization;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Event;
use Tests\TestCase;

class OrganizationTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp() : void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @covers test create an organization and make sure an uuid is created
     * and name is created
     */
    public function test_create_organization() {
        $event = Event::fake();

        $org = factory(Organization::class)->create();
        $this->assertTrue(strlen($org->name) > 0,
            "Organization doesn't have a valid name");
        $this->assertStringMatchesFormat("%x-%x-%x-%x-%x", $org->uuid,
            "Organization doesn't have a valid uuid");

        $event->assertDispatched(OrganizationCreatedEvent::class,
            function(OrganizationCreatedEvent $event) use ($org) {
                return $org->uuid == $event->organization->uuid;
            });
    }
}
