<?php

namespace Tests\Unit;

use App\Organization;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

class OrganizationTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp() : void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @covers test organization
     */
    public function test_organization() {
        $org = new Organization([
            "name" => "Mega Archive"
        ]);
        dump($org);
        $org->save();
    }
}
