<?php

namespace Tests\Unit;

use App\Organization;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

class OrganizationTest extends TestCase
{
    use DatabaseTransactions;

    protected function setUp() : void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @covers test create an organization and make sure an uuid is created
     */
    public function test_create_organization_with_an_uuid() {
        $org = factory(Organization::class)->create();
        $this->assertStringMatchesFormat("%x-%x-%x-%x-%x", $org->uuid);
    }
}
