<?php

namespace Tests\Unit;

use App\Organization;
use App\Events\OrganizationCreatedEvent;
use App\Listeners\OrganizationCreatedListener;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;
use Log;

class OrganizationCreatedListenerTest extends TestCase
{

    use DatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test event listener when when receiving an OrganizationCreatedEvent and validate the log is being written to
     */
    public function test_handle_OrganizationCreatedEvent_and_validate_log() {

       Log::shouldReceive('info')
            ->once()
            ->withArgs(function ($message) {
                return str_contains($message, 'Organization') !== false;
            });

        $org = factory(Organization::class)->make();
        $listener = new OrganizationCreatedListener();
        $listener->handle(new OrganizationCreatedEvent($org));
    }

    /**
     * @test integration by sending an OrganizationCreatedEvent and validate the log is being written to
     */
    public function test_integration_by_sending_an_OrganizationCreatedEvent_and_validate_log() {

        Log::shouldReceive('info')
            ->once()
            ->withArgs(function ($message) {
                return str_contains($message, 'Organization') !== false;
            });

        factory(Organization::class)->create();
    }
}
